/**
* @brief Write a new pattern generated at user defined memory location
*
* @author Ayush Dhoot and Shubham Jaiswal
*/


#include "writepattern.h"

int pattern_wrote = 0;

int write_pattern()
{
	uint32_t *rand_addr;
	uint32_t *i, *j;
	int choice, offset, valid_n = 0, words_available = 0, input_no_words = 0;
	long int seed;
	double rand_pattern;

	if(first_ptr == NULL)  // Check if any memory block is allocated or not.
	{
		PRINTF("\n\rNo memory block is allocated. Please allocate a memory block first.\n");
		return -1;  // Change it with return later on.
	}
	else
	{
		PRINTF("\n\rAllocated memory addresses on which random psuedo number can be written:\n"); // print the address of allocated blocks
		for(i = first_ptr; i <= last_ptr; i++)
		{
			PRINTF("\n\r\n%p",i);
		}
		
		PRINTF("\n\r\n\nPlease select one of following ways to specify the address:"
				"\n\r1.Type the address at which you wish to write the data"
				"\n\r2.Give an offset from %p"
				"\n\r3.Exit command", first_ptr);

		while(1)  // Ask user the address of the block at which he/she wishes to write the data.
		{
			SCANF("%d",&choice);
			PRINTF("\n\r\t%d",choice);

			switch(choice)
			{
				case 1:
				PRINTF("\n\rEnter the address of memory block of which you wish to see the data\n");
				SCANF("%p", &rand_addr);
				break;

				case 2:
				PRINTF("\n\rEnter the offset from memory address %p:", first_ptr);
				SCANF("%d", &offset);
				PRINTF("\t%d", offset);
				rand_addr = first_ptr + offset;
				break;

				case 3:
				return 0;

				default:
				PRINTF("\n\rNot a valid input.Please try again with a valid Input or enter 3 to input another command:\n");
			}

			if(choice == 1 || choice == 2)
			{
				break;
			}
		}

		//Ask user the number of blocks at which he/she wishes to write the pseudo random data.
		PRINTF("\n\rEnter the no of word blocks data you wish to write random pattern at:");
		SCANF("%d", &input_no_words);
		PRINTF("\t%d",input_no_words);

		PRINTF("\n\rEnter the seed value:"); //Ask user to enter the seed value to generate the random number.

#ifdef LINUX
		SCANF("%ld", &seed);
#endif

#ifdef KL25Z
		SCANF("%d", &seed);
		PRINTF("\t%d", seed);
#endif 
		//Check if the address provided by the user is among the allocated memory addresses.
		for(i = first_ptr;i <= last_ptr; i++)
		{		
			if(i == rand_addr)		
			{
				for (j = rand_addr; j <= last_ptr; j++)
				{
					words_available++;
				}
				if(input_no_words <= words_available) // check if the number of blocks demanded by user fall within the number of allocated blocks.
				{
#ifdef LINUX
					clock_t start = clock();  //start timer
#endif

#ifdef KL25Z
					SysTick_Config(16000000);
#endif
					for(; input_no_words > 0 ; input_no_words--) // Write pseudo random number at the requested memory blocks.
					{
						//Algorithm to generate pseudo random number.
						const long Q = MODULUS / MULTIPLIER;
  						const long R = MODULUS % MULTIPLIER;
				        long t;

						t = MULTIPLIER * (seed % Q) - R * (seed / Q);
						if (t > 0)
						{
							seed = t;
						}
						else
						{ 
							seed = t + MODULUS;
						}

						rand_pattern = ((double) seed / MODULUS);
#ifdef KL25Z
						PRINTF("\n\rRandom number generated is %d \n",(long int)(rand_pattern * 1000000)); // Multiplying Random number generated by a million to convert it to an integer.
#endif
#ifdef LINUX
						PRINTF("\n\rRandom number generated is %ld \n",(long int)(rand_pattern * 1000000)); // Multiplying Random number generated by a million to convert it to an integer.
#endif
						*i = (rand_pattern * 1000000);
						i++;
						PRINTF("\n\rRandom pattern stored in memory.\n");
					}

#ifdef KL25Z
					uint32_t count = 16000000 - SysTick->VAL;
					SysTick->CTRL = 0;
					float timetaken = ((0.047619)*count);
					PRINTF("\n\r\nTime taken to write random pattern at specified memory address(es): %f micro-seconds",timetaken);
#endif

#ifdef LINUX
					clock_t end = clock();  //end timer
					PRINTF("\n\r\nTime taken to write random pattern at specified memory address(es):%f seconds",(double)(end - start) / CLOCKS_PER_SEC);
					PRINTF("\n\r\n");
#endif

				}
				else
				{
					PRINTF("\n\rAsked number of blocks not avaible from the desired address.\n");
					return -1;
				}
				break;
			} 
			else
			{
			 	valid_n++;					
			}
		}

		if(valid_n == mem_allocate)					//Condition to check whether entered address is valid or not
   		{
			PRINTF("\n\r\nThe address entered is not a valid address");
			PRINTF("\n\r\n");
			return -1;
		}
	}
	pattern_wrote = 1;
	return 0;
}
